apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::359304582046:role/eksctl-shukawam-cluster-cluster-ServiceRole-Sj7BZzL9oQPX
  name: kong-cluster-sa
