apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: shukawam-cluster
  region: us-east-1
  version: "1.32"
  tags:
    owner: shukawam
    environment: development
nodeGroups:
  - name: shukawam-nodegroup
    instanceType: m5.large
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    iam:
      withAddonPolicies:
        autoScaler: true
        cloudWatch: true
        ebs: true
        albIngress: true
