apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kong-mesh-service-monitor
  labels:
    release: kube-prometheus-stack
spec:
  endpoints:
    - path: /metrics
      port: diagnostics
  selector:
    matchLabels:
      app: kong-mesh-control-plane
      prometheus.io/scrape: "true"
  namespaceSelector:
    matchNames:
      - kong-mesh-system
