apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    repoURL: https://charts.jetstack.io
    targetRevision: v1.18.0
    chart: cert-manager
    helm:
      values: |
        installCRDs: true
        prometheus:
          servicemonitor:
            enabled: true
            namespace: observability
            labels:
              release: kube-prometheus-stack
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: management
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
