apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k6-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 3.16.0
    chart: k6-operator
  destination:
    namespace: k6
    server: https://kubernetes.default.svc
  project: management
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
