apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-ingress-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: kong
  source:
    repoURL: https://charts.konghq.com
    chart: ingress
    targetRevision: 0.20.0
    helm:
      values: |
        gateway:
          serviceMonitor:
            enabled: true
            labels:
              release: kube-prometheus-stack
          env:
            tracing_instrumentations: all
            tracing_sampling_rate: 1.0 # for demo
  destination:
    server: https://kubernetes.default.svc
    namespace: kong
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
