apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-mesh
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: kong
  source:
    repoURL: https://kong.github.io/kong-mesh-charts
    chart: kong-mesh
    targetRevision: 2.9.5
    helm:
      values: |
        kuma:
          controlPlane:
            ingress:
              enabled: true
              ingressClassName: kong
              hostName: kong-mesh.shukawam.me
              annotations:
                cert-manager.io/cluster-issuer: letsencrypt-prod
            serviceMonitor:
              enabled: true
              labels:
                release: kube-prometheus-stack
            tls:
              general:
                secretName: shukawam-me-kong-mesh-tls
  destination:
    server: https://kubernetes.default.svc
    namespace: kong-mesh-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
