apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-mesh
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: kong
  source:
    repoURL: https://kong.github.io/kong-mesh-charts
    chart: kong-mesh
    targetRevision: 2.9.5
    helm:
      values: |
        kuma:
          controlPlane:
            extraLabels:
              prometheus.io/scrape: true
            secrets:
              - Env: KMESH_LICENSE_INLINE
                Secret: kong-mesh-license
                Key: license.json
            envVars:
              - name: KUMA_TRACING_OPENTELEMETRY_ENABLED
                value: true
            ingress:
              enabled: true
              ingressClassName: kong
              hostName: kong-mesh.shukawam.me
  destination:
    server: https://kubernetes.default.svc
    namespace: kong-mesh-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
