apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: observability
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 73.1.0
    helm:
      values: |
        prometheus:
          prometheusSpec:
            scrapeInterval: 10s
            evaluationInterval: 30s
        grafana:
          ingress:
            enabled: true
            ingressClassName: kong
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - grafana.shukawam.me
            tls:
              - secretName: shukawam-me-grafana-tls
                hosts:
                  - grafana.shukawam.me
          grafana.ini:
            server:
              root_url: https://grafana.shukawam.me
            auth.generic_oauth:
              enabled: true
              name: Auth0
              allow_sign_up: true
              scopes: openid profile email offline_access
              auth_url: https://auth0.shukawam.me/authorize
              token_url: https://auth0.shukawam.me/token
              api_url: https://auth0.shukawam.me/userinfo
              use_pkce: true
              use_refresh_token: true
              role_attribute_path: contains(https://shukawam.me/groups[*], 'grafana-admins') && 'Admin' || contains(https://shukawam.me/groups[*], 'grafana-guests') && 'Editor' || 'Viewer'
          envValueFrom:
            GF_AUTH_GENERIC_OAUTH_CLIENT_ID:
              secretKeyRef:
                name: grafana-auth0-secret
                key: client_id
            GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET:
              secretKeyRef:
                name: grafana-auth0-secret
                key: client_secret
          persistence:
            enabled: true  # enable persistence using Persistent Volumes
          dashboardProviders:
            dashboardproviders.yaml:
              apiVersion: 1
              providers:
              - name: 'default' # Configure a dashboard provider file to
                orgId: 1        # put Kong dashboard into.
                folder: ''
                type: file
                disableDeletion: false
                editable: true
                options:
                  path: /var/lib/grafana/dashboards/default
          datasources:
            datasources.yaml:
              apiVersion: 1
              datasources:
                - name: Prometheus
                  type: prometheus
                  url: http://kube-prometheus-stack-prometheus:9090
                  isDefault: true
                - name: Loki
                  type: loki
                  url: http://loki-stack:3100
                - name: Tempo
                  type: tempo
                  url: http://tempo:3100
          dashboards:
            default:
              kong-dashboard:
                gnetId: 7424  # Install the following Grafana dashboard in the
                revision: 11  # instance: https://grafana.com/dashboards/7424
                datasource: Prometheus
              kic-dashboard:
                gnetId: 15662
                datasource: Prometheus
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
