apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kong-enterprise-license
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: kong-enterprise-license
    creationPolicy: Owner
  data:
    - secretKey: secret-key-to-be-managed
      remoteRef:
        key: shukawam/kong/enterprise-license-data
  dataFrom:
    - extract:
        key: enterprise-license-data
