kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: kong-gateway
spec:
  gatewayClassName: kong
  listeners:
    - name: http
      hostname: "*.shukawam.me"
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              shared-gateway-access: "true"
    # - name: https
    #   hostname: "*.shukawam.me"
    #   protocol: HTTPS
    #   port: 443
    #   allowedRoutes:
    #     namespaces:
    #       from: Selector
    #       selector:
    #         matchLabels:
    #           shared-gateway-access: "true"
