kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: kong-gateway
spec:
  gatewayClassName: kong
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              shared-gateway-access: "true"
