apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: opentelemetry-plugin
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
plugin: opentelemetry
config:
  # gRPC endpoint is not supported by the OpenTelemetry plugin, so we use HTTP endpoints
  traces_endpoint: http://opentelemetry-collector.observability.svc.cluster.local:4318/v1/traces
  logs_endpoint: http://opentelemetry-collector.observability.svc.cluster.local:4318/v1/logs
