name: Sync decK config(Gorilla Market)

on:
  push:
    paths:
      - deck/global/*.yaml
      - deck/gorilla-market/*.yaml
      - .github/workflows/sync-gorilla-market.yaml
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup deck
        uses: kong/setup-deck@v1
        with:
          deck-version: 1.49.0
      - name: Merge global config
        run: |
          deck file merge \
            -o deck/gorilla-market/merged.yaml \
            deck/global/kong.yaml \
            deck/gorilla-market/kong.yaml
      - name: Add tag
        run: |
          deck file add-tags -s deck/gorilla-market/merged.yaml \
            gorilla-market
          deck file add-tags -s deck/konbot/merged.yaml \
            konbot
      - name: Diff current environment
        run: |
          deck gateway diff deck/gorilla-market/kong.yaml \
            --select-tag gorilla-market \
            --konnect-token ${{ secrets.KONNECT_TOKEN }}
      - name: Diff current environment(Konbot)
        run: |
          deck gateway diff deck/konbot/kong.yaml \
            --select-tag konbot \
            --konnect-token ${{ secrets.KONNECT_TOKEN }}
      - name: Sync gateway config
        run: |
          deck gateway sync deck/gorilla-market/kong.yaml \
            --select-tag gorilla-market \
            --konnect-token ${{ secrets.KONNECT_TOKEN }}
